### ISSUE TITLE
The graph page could use a little whitespace to easier see the scripts link at bottom

### ISSUE THREAD

**Issue by jeff-luszcz** [curl/stats#11]
When viewing the graphs page I was interested in seeing what was used to generate the graphs and scrolled to the bottom.
I saw the "generated using XYZ" link as expected but it was hard to read due to a lack of whitespace and Safari placing a hover link over the text.

Low priority but I wonder if this link could be given better visibility with a little whitespace after it?

<img width="760" alt="Screen Shot 2021-11-19 at 2 25 19 PM" src="https://user-images.githubusercontent.com/8672214/142699412-42ea7d72-0cb4-4ee7-9c3b-5a25d8c56efa.png">

**Comment by bagder** [comment]
oh indeed...

**Comment by bagder** [comment]
Thanks. Simplest possible: I've added two `<p>` down there which should push it down a bit.

**Comment by bagder** [comment]
Hm, not sure it made much difference...

**Comment by bagder** [comment]
ok, did it differently and now verified that it also actually worked.
