### ISSUE TITLE
Dashboard chart fonts too small to be legible

### ISSUE THREAD

**Issue by jay** [curl/stats#2]
I have no idea what anything says. Here is a screenshot of the page at 125% in Chrome at 1920x1080.

![toosmall](https://user-images.githubusercontent.com/965580/77221215-0f69bc00-6b1e-11ea-86ac-1ee9f5ba93b2.png)

**Comment by bagder** [comment]
You think they need to be readable at that size?

**Comment by bagder** [comment]
Probably. I'll try to just enlarge the titles.

**Comment by bagder** [comment]
I doubled the size to 48, I think it looks better.
