### ISSUE TITLE
bug in graph

### ISSUE THREAD

**Issue by REGI2210** [curl/stats#8]
MINHA REDE SOCIAL

**Comment by REGI2210** [comment]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 | Parse.Cloud.define("updatePlayer", async(request) => {   const attributes = request.params.attributes;   const yearOfBirth = request.params.yearOfBirth;    const query = new Parse.Query("SoccerPlayers");   query.equalTo('yearOfBirth', yearOfBirth);   const results = await query.find();    for (let i = 0; i < results.length; i++) {     let object = results[i];     object.add("attributes", attributes);     try{       await object.save();     } catch (e){       console.log(`Error while trying to save ${object.id}. Message: ${e.message}`)     }   }    return results });
-- | --

**Comment by jay** [comment]
?

**Comment by bagder** [comment]
abuse
